### ISSUE TITLE
JS and Express Fundamentals and Formatting

### ISSUE THREAD

**Issue by tbergen1** [KaiBi/codecademy-expresso#4]
Your code is well done.  The JS code is formatted well and uses descriptive variable names for great readability.  You also exhibited proper use of language features as well as Express features like routers and middleware.  One suggestion would be to use JavaScript's ES6 string templates when building strings.  You can use ternary operators within string templates, so it will create more concise queries in your code instead of having to concatenate them with "+".

**Comment by KaiBi** [comment]
True. I did not think of that. Thanks for the suggestion.
